apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque
data:
  server: <base64-encoded-server-name>
  database: <base64-encoded-database-name>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
