apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryyyz6083.azurecr.io/microservices/tripviewer:v1
          ports:
            - containerPort: 80
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  key: SQL_SERVER
                  name: sql-secret
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: sql-secret
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql-secret
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-service.microservices.svc.cluster.local
            - name: TRIPS_API_ENDPOINT
              value: http://trips-service.microservices.svc.cluster.local
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  selector:
    app: tripviewer
  ports:
  - port: 80
