apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque
data:
  server: c3Fsc2VydmVya3p6ODIyMi5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  database: bXlkcml2aW5nREI=
  username: c3FsYWRtaW55WXo2MDgz
  password: U1FMMjAyMyE=
