apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque
data:
  SQL_SERVER: c3Fsc2VydmVya3p6ODIyMi5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  database: bXlkcml2aW5nREI=
  SQL_USER: c3FsYWRtaW55WXo2MDgz
  SQL_PASSWORD: U1FMMjAyMyE=
