apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
        - name: user-java
          image: registryyyz6083.azurecr.io/user-java:v1
          ports:
            - containerPort: 8080
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  key: SQL_SERVER
                  name: sql-secret
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: sql-secret
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql-secret
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
spec:
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080