apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
        - name: user-java
          image: registryyyz6083.azurecr.io/user-java:v1
          ports:
            - containerPort: 8080
          env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_SERVER
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_PASSWORD
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  type: ClusterIP
  ports:
 - port: 80
  selector:
    app: user-java
