apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryyyz6083.azurecr.io/trips:v1
          ports:
            - containerPort: 8080
          env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_SERVER
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_PASSWORD
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: trips
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

