apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: registryyyz6083.azurecr.io/microservices/poi:v1
          ports:
            - containerPort: 8080
          env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_SERVER
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: SQL_PASSWORD
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

