apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryyyz6083.azurecr.io/microservices/userprofile:v1 tripinsights/userprofile
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sql-secret-volume
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
