apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryyyz6083.azurecr.io/microservices/userprofile:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sql-secret-volume
              mountPath: /app/secrets
              readOnly: true
          env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: secret
                key: SQL_SERVER
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: SQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
