apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryyyz6083.azurecr.io/microservices/userprofile:v1
          ports:
            - containerPort: 80
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  key: SQL_SERVER
                  name: sql-secret
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: sql-secret
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql-secret
      volumes:
        - name: sql-secret-volume
          secret:
            secretName: sql-secret
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  ports:
  - port: 80